# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

workspace 'Example-Service'
project 'Example-Service-Swift.xcodeproj'
project 'Example-Service-Objc.xcodeproj'

def common_pods
  pod 'Map4dServices', '~> 2.4.0'
end 

target 'Example-Service-Swift' do
project 'Example-Service-Swift.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-Service-Swift
  common_pods
end

target 'Example-Service-Objc' do
#roject 'Example-Service-Objc.xcodeproj'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example-Service-Swift
  common_pods
end
