#if TARGET_OS_SIMULATOR
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef MAP4DSERVICES_SWIFT_H
#define MAP4DSERVICES_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Map4dServices",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class MFQueryAutocompletionOptions;
@class MFPlace;
@protocol MFServiceError;
@protocol MFServiceTask;

SWIFT_CLASS("_TtC13Map4dServices21MFAutocompleteService")
@interface MFAutocompleteService : NSObject
- (id <MFServiceTask> _Nullable)getQueryPredictionsWithOptions:(MFQueryAutocompletionOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocation;
@class MFWaypoint;
enum MFTravelMode : NSInteger;
enum MFRouteWeighting : NSInteger;

SWIFT_CLASS("_TtC13Map4dServices18MFDirectionOptions")
@interface MFDirectionOptions : NSObject
@property (nonatomic, strong) CLLocation * _Nullable origin;
@property (nonatomic, strong) CLLocation * _Nullable destination;
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nullable waypoints;
@property (nonatomic) enum MFTravelMode mode;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic) enum MFRouteWeighting weighting;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MFRoute;

SWIFT_CLASS("_TtC13Map4dServices18MFDirectionService")
@interface MFDirectionService : NSObject
- (id <MFServiceTask> _Nullable)routeWithOptions:(MFDirectionOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFRoute *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MFDistanceMatrixRow;

SWIFT_CLASS("_TtC13Map4dServices16MFDistanceMatrix")
@interface MFDistanceMatrix : NSObject
@property (nonatomic, copy) NSArray<MFDistanceMatrixRow *> * _Nullable rows;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end

@class MFDistanceMatrixElement;

SWIFT_CLASS_NAMED("Row")
@interface MFDistanceMatrixRow : NSObject
@property (nonatomic, copy) NSArray<MFDistanceMatrixElement *> * _Nullable elements;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end

@class MFDistanceMatrixInfo;

SWIFT_CLASS_NAMED("Element")
@interface MFDistanceMatrixElement : NSObject
@property (nonatomic, strong) MFDistanceMatrixInfo * _Nullable distance;
@property (nonatomic, strong) MFDistanceMatrixInfo * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Info")
@interface MFDistanceMatrixInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) double value;
@end


SWIFT_CLASS("_TtC13Map4dServices23MFDistanceMatrixOptions")
@interface MFDistanceMatrixOptions : NSObject
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nonnull origins;
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nonnull destinations;
@property (nonatomic) enum MFTravelMode mode;
@property (nonatomic, copy) NSString * _Nonnull language;
- (nonnull instancetype)initWithOrigins:(NSArray<MFWaypoint *> * _Nonnull)origins destinations:(NSArray<MFWaypoint *> * _Nonnull)destinations OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices23MFDistanceMatrixService")
@interface MFDistanceMatrixService : NSObject
- (id <MFServiceTask> _Nullable)getDistanceMatrixWithOptions:(MFDistanceMatrixOptions * _Nonnull)options completion:(void (^ _Nonnull)(MFDistanceMatrix * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices16MFGeocodeOptions")
@interface MFGeocodeOptions : NSObject
@property (nonatomic, strong) CLLocation * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) CLLocation * _Nullable northEast;
@property (nonatomic, strong) CLLocation * _Nullable southWest;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices16MFGeocodeService")
@interface MFGeocodeService : NSObject
- (id <MFServiceTask> _Nullable)geocodeWithOptions:(MFGeocodeOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MFManeuver, open) {
  MFManeuverNone = 0,
  MFManeuverKeepLeft = 1,
  MFManeuverKeepRight = 2,
  MFManeuverTurnSharpRight = 3,
  MFManeuverTurnSharpLeft = 4,
  MFManeuverTurnLeft = 5,
  MFManeuverTurnRight = 6,
  MFManeuverTurnSlightLeft = 7,
  MFManeuverTurnSlightRight = 8,
  MFManeuverContinueOnStreet = 9,
  MFManeuverFinish = 10,
  MFManeuverRoundaboutLeft = 11,
  MFManeuverRoundaboutRight = 12,
  MFManeuverReachedVia = 13,
};


SWIFT_CLASS("_TtC13Map4dServices21MFNearbySearchOptions")
@interface MFNearbySearchOptions : NSObject
@property (nonatomic) CLLocationCoordinate2D location;
@property (nonatomic) NSInteger radius;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithLocation:(CLLocationCoordinate2D)location radius:(NSInteger)radius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices7MFPlace")
@interface MFPlace : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic) CLLocationCoordinate2D location;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFPlaceMetadata;
@class MFPlacePhotoInfo;
@class MFPlaceAddressComponent;

SWIFT_CLASS("_TtC13Map4dServices14MFPlaceDetails")
@interface MFPlaceDetails : MFPlace
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSArray<MFPlaceMetadata *> * _Nullable metadatas;
@property (nonatomic, copy) NSArray<MFPlacePhotoInfo *> * _Nullable photos;
@property (nonatomic, copy) NSArray<MFPlaceAddressComponent *> * _Nullable addressComponents;
@property (nonatomic, copy) NSString * _Nullable objectId;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("PhotoInfo")
@interface MFPlacePhotoInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, copy) NSString * _Nullable name;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Metadata")
@interface MFPlaceMetadata : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic) NSInteger order;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("AddressComponent")
@interface MFPlaceAddressComponent : NSObject
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@end

@class MFTextSearchOptions;
@class MFViewboxSearchOptions;

SWIFT_CLASS("_TtC13Map4dServices15MFPlacesService")
@interface MFPlacesService : NSObject
- (id <MFServiceTask> _Nullable)getDetailsWithPlaceId:(NSString * _Nonnull)placeId completion:(void (^ _Nonnull)(MFPlaceDetails * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)textSearchWithOptions:(MFTextSearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)nearbySearchWithOptions:(MFNearbySearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)viewboxSearchWithOptions:(MFViewboxSearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices28MFQueryAutocompletionOptions")
@interface MFQueryAutocompletionOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, strong) CLLocation * _Nullable location;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text location:(CLLocation * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFRouteLeg;
@class MFRouteInfo;

SWIFT_CLASS("_TtC13Map4dServices7MFRoute")
@interface MFRoute : NSObject
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull overviewCoordinates;
@property (nonatomic, copy) NSArray<MFRouteLeg *> * _Nonnull legs;
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull snappedCoordinates;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Info")
@interface MFRouteInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) double value;
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end

@class MFRouteStep;

SWIFT_CLASS_NAMED("Leg")
@interface MFRouteLeg : NSObject
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic, copy) NSString * _Nonnull startAddress;
@property (nonatomic, copy) NSString * _Nonnull endAddress;
@property (nonatomic) CLLocationCoordinate2D startCoordinate;
@property (nonatomic) CLLocationCoordinate2D endCoordinate;
@property (nonatomic, copy) NSArray<MFRouteStep *> * _Nonnull steps;
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Step")
@interface MFRouteStep : NSObject
@property (nonatomic, copy) NSString * _Nonnull instruction;
@property (nonatomic) enum MFManeuver maneuver;
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic) CLLocationCoordinate2D startCoordinate;
@property (nonatomic) CLLocationCoordinate2D endCoordinate;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull coordinates;
@property (nonatomic, copy) NSString * _Nonnull streetName;
@property (nonatomic) enum MFTravelMode mode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MFRouteWeighting, "Weighting", open) {
  MFRouteWeightingShortest = 0,
  MFRouteWeightingFastest = 1,
  MFRouteWeightingBalance = 2,
};


SWIFT_PROTOCOL("_TtP13Map4dServices14MFServiceError_")
@protocol MFServiceError
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


SWIFT_PROTOCOL("_TtP13Map4dServices13MFServiceTask_")
@protocol MFServiceTask
- (void)abort;
@end


SWIFT_CLASS("_TtC13Map4dServices19MFTextSearchOptions")
@interface MFTextSearchOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic, strong) CLLocation * _Nullable location;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, MFTravelMode, open) {
  MFTravelModeCar = 0,
  MFTravelModeBike = 1,
  MFTravelModeFoot = 2,
};


SWIFT_CLASS("_TtC13Map4dServices22MFViewboxSearchOptions")
@interface MFViewboxSearchOptions : NSObject
@property (nonatomic) CLLocationCoordinate2D southWest;
@property (nonatomic) CLLocationCoordinate2D northEast;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithSouthWest:(CLLocationCoordinate2D)southWest northEast:(CLLocationCoordinate2D)northEast OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices10MFWaypoint")
@interface MFWaypoint : NSObject
@property (nonatomic) CLLocationCoordinate2D coordinate;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate name:(NSString * _Nullable)name OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (MFWaypoint * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface NSError (SWIFT_EXTENSION(Map4dServices)) <MFServiceError>
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


@interface NSURLSessionTask (SWIFT_EXTENSION(Map4dServices)) <MFServiceTask>
- (void)abort;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef MAP4DSERVICES_SWIFT_H
#define MAP4DSERVICES_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Map4dServices",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class MFQueryAutocompletionOptions;
@class MFPlace;
@protocol MFServiceError;
@protocol MFServiceTask;

SWIFT_CLASS("_TtC13Map4dServices21MFAutocompleteService")
@interface MFAutocompleteService : NSObject
- (id <MFServiceTask> _Nullable)getQueryPredictionsWithOptions:(MFQueryAutocompletionOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocation;
@class MFWaypoint;
enum MFTravelMode : NSInteger;
enum MFRouteWeighting : NSInteger;

SWIFT_CLASS("_TtC13Map4dServices18MFDirectionOptions")
@interface MFDirectionOptions : NSObject
@property (nonatomic, strong) CLLocation * _Nullable origin;
@property (nonatomic, strong) CLLocation * _Nullable destination;
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nullable waypoints;
@property (nonatomic) enum MFTravelMode mode;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic) enum MFRouteWeighting weighting;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MFRoute;

SWIFT_CLASS("_TtC13Map4dServices18MFDirectionService")
@interface MFDirectionService : NSObject
- (id <MFServiceTask> _Nullable)routeWithOptions:(MFDirectionOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFRoute *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MFDistanceMatrixRow;

SWIFT_CLASS("_TtC13Map4dServices16MFDistanceMatrix")
@interface MFDistanceMatrix : NSObject
@property (nonatomic, copy) NSArray<MFDistanceMatrixRow *> * _Nullable rows;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end

@class MFDistanceMatrixElement;

SWIFT_CLASS_NAMED("Row")
@interface MFDistanceMatrixRow : NSObject
@property (nonatomic, copy) NSArray<MFDistanceMatrixElement *> * _Nullable elements;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end

@class MFDistanceMatrixInfo;

SWIFT_CLASS_NAMED("Element")
@interface MFDistanceMatrixElement : NSObject
@property (nonatomic, strong) MFDistanceMatrixInfo * _Nullable distance;
@property (nonatomic, strong) MFDistanceMatrixInfo * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Info")
@interface MFDistanceMatrixInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) double value;
@end


SWIFT_CLASS("_TtC13Map4dServices23MFDistanceMatrixOptions")
@interface MFDistanceMatrixOptions : NSObject
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nonnull origins;
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nonnull destinations;
@property (nonatomic) enum MFTravelMode mode;
@property (nonatomic, copy) NSString * _Nonnull language;
- (nonnull instancetype)initWithOrigins:(NSArray<MFWaypoint *> * _Nonnull)origins destinations:(NSArray<MFWaypoint *> * _Nonnull)destinations OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices23MFDistanceMatrixService")
@interface MFDistanceMatrixService : NSObject
- (id <MFServiceTask> _Nullable)getDistanceMatrixWithOptions:(MFDistanceMatrixOptions * _Nonnull)options completion:(void (^ _Nonnull)(MFDistanceMatrix * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices16MFGeocodeOptions")
@interface MFGeocodeOptions : NSObject
@property (nonatomic, strong) CLLocation * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) CLLocation * _Nullable northEast;
@property (nonatomic, strong) CLLocation * _Nullable southWest;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices16MFGeocodeService")
@interface MFGeocodeService : NSObject
- (id <MFServiceTask> _Nullable)geocodeWithOptions:(MFGeocodeOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MFManeuver, open) {
  MFManeuverNone = 0,
  MFManeuverKeepLeft = 1,
  MFManeuverKeepRight = 2,
  MFManeuverTurnSharpRight = 3,
  MFManeuverTurnSharpLeft = 4,
  MFManeuverTurnLeft = 5,
  MFManeuverTurnRight = 6,
  MFManeuverTurnSlightLeft = 7,
  MFManeuverTurnSlightRight = 8,
  MFManeuverContinueOnStreet = 9,
  MFManeuverFinish = 10,
  MFManeuverRoundaboutLeft = 11,
  MFManeuverRoundaboutRight = 12,
  MFManeuverReachedVia = 13,
};


SWIFT_CLASS("_TtC13Map4dServices21MFNearbySearchOptions")
@interface MFNearbySearchOptions : NSObject
@property (nonatomic) CLLocationCoordinate2D location;
@property (nonatomic) NSInteger radius;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithLocation:(CLLocationCoordinate2D)location radius:(NSInteger)radius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices7MFPlace")
@interface MFPlace : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic) CLLocationCoordinate2D location;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFPlaceMetadata;
@class MFPlacePhotoInfo;
@class MFPlaceAddressComponent;

SWIFT_CLASS("_TtC13Map4dServices14MFPlaceDetails")
@interface MFPlaceDetails : MFPlace
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSArray<MFPlaceMetadata *> * _Nullable metadatas;
@property (nonatomic, copy) NSArray<MFPlacePhotoInfo *> * _Nullable photos;
@property (nonatomic, copy) NSArray<MFPlaceAddressComponent *> * _Nullable addressComponents;
@property (nonatomic, copy) NSString * _Nullable objectId;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("PhotoInfo")
@interface MFPlacePhotoInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, copy) NSString * _Nullable name;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Metadata")
@interface MFPlaceMetadata : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic) NSInteger order;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("AddressComponent")
@interface MFPlaceAddressComponent : NSObject
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@end

@class MFTextSearchOptions;
@class MFViewboxSearchOptions;

SWIFT_CLASS("_TtC13Map4dServices15MFPlacesService")
@interface MFPlacesService : NSObject
- (id <MFServiceTask> _Nullable)getDetailsWithPlaceId:(NSString * _Nonnull)placeId completion:(void (^ _Nonnull)(MFPlaceDetails * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)textSearchWithOptions:(MFTextSearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)nearbySearchWithOptions:(MFNearbySearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)viewboxSearchWithOptions:(MFViewboxSearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices28MFQueryAutocompletionOptions")
@interface MFQueryAutocompletionOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, strong) CLLocation * _Nullable location;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text location:(CLLocation * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFRouteLeg;
@class MFRouteInfo;

SWIFT_CLASS("_TtC13Map4dServices7MFRoute")
@interface MFRoute : NSObject
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull overviewCoordinates;
@property (nonatomic, copy) NSArray<MFRouteLeg *> * _Nonnull legs;
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull snappedCoordinates;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Info")
@interface MFRouteInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) double value;
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end

@class MFRouteStep;

SWIFT_CLASS_NAMED("Leg")
@interface MFRouteLeg : NSObject
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic, copy) NSString * _Nonnull startAddress;
@property (nonatomic, copy) NSString * _Nonnull endAddress;
@property (nonatomic) CLLocationCoordinate2D startCoordinate;
@property (nonatomic) CLLocationCoordinate2D endCoordinate;
@property (nonatomic, copy) NSArray<MFRouteStep *> * _Nonnull steps;
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Step")
@interface MFRouteStep : NSObject
@property (nonatomic, copy) NSString * _Nonnull instruction;
@property (nonatomic) enum MFManeuver maneuver;
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic) CLLocationCoordinate2D startCoordinate;
@property (nonatomic) CLLocationCoordinate2D endCoordinate;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull coordinates;
@property (nonatomic, copy) NSString * _Nonnull streetName;
@property (nonatomic) enum MFTravelMode mode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MFRouteWeighting, "Weighting", open) {
  MFRouteWeightingShortest = 0,
  MFRouteWeightingFastest = 1,
  MFRouteWeightingBalance = 2,
};


SWIFT_PROTOCOL("_TtP13Map4dServices14MFServiceError_")
@protocol MFServiceError
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


SWIFT_PROTOCOL("_TtP13Map4dServices13MFServiceTask_")
@protocol MFServiceTask
- (void)abort;
@end


SWIFT_CLASS("_TtC13Map4dServices19MFTextSearchOptions")
@interface MFTextSearchOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic, strong) CLLocation * _Nullable location;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, MFTravelMode, open) {
  MFTravelModeCar = 0,
  MFTravelModeBike = 1,
  MFTravelModeFoot = 2,
};


SWIFT_CLASS("_TtC13Map4dServices22MFViewboxSearchOptions")
@interface MFViewboxSearchOptions : NSObject
@property (nonatomic) CLLocationCoordinate2D southWest;
@property (nonatomic) CLLocationCoordinate2D northEast;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithSouthWest:(CLLocationCoordinate2D)southWest northEast:(CLLocationCoordinate2D)northEast OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices10MFWaypoint")
@interface MFWaypoint : NSObject
@property (nonatomic) CLLocationCoordinate2D coordinate;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate name:(NSString * _Nullable)name OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (MFWaypoint * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface NSError (SWIFT_EXTENSION(Map4dServices)) <MFServiceError>
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


@interface NSURLSessionTask (SWIFT_EXTENSION(Map4dServices)) <MFServiceTask>
- (void)abort;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef MAP4DSERVICES_SWIFT_H
#define MAP4DSERVICES_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Map4dServices",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class MFQueryAutocompletionOptions;
@class MFPlace;
@protocol MFServiceError;
@protocol MFServiceTask;

SWIFT_CLASS("_TtC13Map4dServices21MFAutocompleteService")
@interface MFAutocompleteService : NSObject
- (id <MFServiceTask> _Nullable)getQueryPredictionsWithOptions:(MFQueryAutocompletionOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CLLocation;
@class MFWaypoint;
enum MFTravelMode : NSInteger;
enum MFRouteWeighting : NSInteger;

SWIFT_CLASS("_TtC13Map4dServices18MFDirectionOptions")
@interface MFDirectionOptions : NSObject
@property (nonatomic, strong) CLLocation * _Nullable origin;
@property (nonatomic, strong) CLLocation * _Nullable destination;
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nullable waypoints;
@property (nonatomic) enum MFTravelMode mode;
@property (nonatomic, copy) NSString * _Nullable language;
@property (nonatomic) enum MFRouteWeighting weighting;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MFRoute;

SWIFT_CLASS("_TtC13Map4dServices18MFDirectionService")
@interface MFDirectionService : NSObject
- (id <MFServiceTask> _Nullable)routeWithOptions:(MFDirectionOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFRoute *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MFDistanceMatrixRow;

SWIFT_CLASS("_TtC13Map4dServices16MFDistanceMatrix")
@interface MFDistanceMatrix : NSObject
@property (nonatomic, copy) NSArray<MFDistanceMatrixRow *> * _Nullable rows;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end

@class MFDistanceMatrixElement;

SWIFT_CLASS_NAMED("Row")
@interface MFDistanceMatrixRow : NSObject
@property (nonatomic, copy) NSArray<MFDistanceMatrixElement *> * _Nullable elements;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end

@class MFDistanceMatrixInfo;

SWIFT_CLASS_NAMED("Element")
@interface MFDistanceMatrixElement : NSObject
@property (nonatomic, strong) MFDistanceMatrixInfo * _Nullable distance;
@property (nonatomic, strong) MFDistanceMatrixInfo * _Nullable duration;
@property (nonatomic, copy) NSString * _Nullable status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface MFDistanceMatrix (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Info")
@interface MFDistanceMatrixInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) double value;
@end


SWIFT_CLASS("_TtC13Map4dServices23MFDistanceMatrixOptions")
@interface MFDistanceMatrixOptions : NSObject
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nonnull origins;
@property (nonatomic, copy) NSArray<MFWaypoint *> * _Nonnull destinations;
@property (nonatomic) enum MFTravelMode mode;
@property (nonatomic, copy) NSString * _Nonnull language;
- (nonnull instancetype)initWithOrigins:(NSArray<MFWaypoint *> * _Nonnull)origins destinations:(NSArray<MFWaypoint *> * _Nonnull)destinations OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices23MFDistanceMatrixService")
@interface MFDistanceMatrixService : NSObject
- (id <MFServiceTask> _Nullable)getDistanceMatrixWithOptions:(MFDistanceMatrixOptions * _Nonnull)options completion:(void (^ _Nonnull)(MFDistanceMatrix * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices16MFGeocodeOptions")
@interface MFGeocodeOptions : NSObject
@property (nonatomic, strong) CLLocation * _Nullable location;
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, strong) CLLocation * _Nullable northEast;
@property (nonatomic, strong) CLLocation * _Nullable southWest;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices16MFGeocodeService")
@interface MFGeocodeService : NSObject
- (id <MFServiceTask> _Nullable)geocodeWithOptions:(MFGeocodeOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, MFManeuver, open) {
  MFManeuverNone = 0,
  MFManeuverKeepLeft = 1,
  MFManeuverKeepRight = 2,
  MFManeuverTurnSharpRight = 3,
  MFManeuverTurnSharpLeft = 4,
  MFManeuverTurnLeft = 5,
  MFManeuverTurnRight = 6,
  MFManeuverTurnSlightLeft = 7,
  MFManeuverTurnSlightRight = 8,
  MFManeuverContinueOnStreet = 9,
  MFManeuverFinish = 10,
  MFManeuverRoundaboutLeft = 11,
  MFManeuverRoundaboutRight = 12,
  MFManeuverReachedVia = 13,
};


SWIFT_CLASS("_TtC13Map4dServices21MFNearbySearchOptions")
@interface MFNearbySearchOptions : NSObject
@property (nonatomic) CLLocationCoordinate2D location;
@property (nonatomic) NSInteger radius;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithLocation:(CLLocationCoordinate2D)location radius:(NSInteger)radius OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices7MFPlace")
@interface MFPlace : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull address;
@property (nonatomic) CLLocationCoordinate2D location;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFPlaceMetadata;
@class MFPlacePhotoInfo;
@class MFPlaceAddressComponent;

SWIFT_CLASS("_TtC13Map4dServices14MFPlaceDetails")
@interface MFPlaceDetails : MFPlace
@property (nonatomic, copy) NSString * _Nullable desc;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSArray<MFPlaceMetadata *> * _Nullable metadatas;
@property (nonatomic, copy) NSArray<MFPlacePhotoInfo *> * _Nullable photos;
@property (nonatomic, copy) NSArray<MFPlaceAddressComponent *> * _Nullable addressComponents;
@property (nonatomic, copy) NSString * _Nullable objectId;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("PhotoInfo")
@interface MFPlacePhotoInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, copy) NSString * _Nullable name;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Metadata")
@interface MFPlaceMetadata : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull content;
@property (nonatomic) NSInteger order;
@end


@interface MFPlaceDetails (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("AddressComponent")
@interface MFPlaceAddressComponent : NSObject
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSString * _Nonnull type;
@property (nonatomic, copy) NSString * _Nonnull name;
@end

@class MFTextSearchOptions;
@class MFViewboxSearchOptions;

SWIFT_CLASS("_TtC13Map4dServices15MFPlacesService")
@interface MFPlacesService : NSObject
- (id <MFServiceTask> _Nullable)getDetailsWithPlaceId:(NSString * _Nonnull)placeId completion:(void (^ _Nonnull)(MFPlaceDetails * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)textSearchWithOptions:(MFTextSearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)nearbySearchWithOptions:(MFNearbySearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (id <MFServiceTask> _Nullable)viewboxSearchWithOptions:(MFViewboxSearchOptions * _Nonnull)options completion:(void (^ _Nonnull)(NSArray<MFPlace *> * _Nullable, id <MFServiceError> _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13Map4dServices28MFQueryAutocompletionOptions")
@interface MFQueryAutocompletionOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, strong) CLLocation * _Nullable location;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text location:(CLLocation * _Nullable)location OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class MFRouteLeg;
@class MFRouteInfo;

SWIFT_CLASS("_TtC13Map4dServices7MFRoute")
@interface MFRoute : NSObject
@property (nonatomic, copy) NSString * _Nonnull summary;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull overviewCoordinates;
@property (nonatomic, copy) NSArray<MFRouteLeg *> * _Nonnull legs;
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull snappedCoordinates;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Info")
@interface MFRouteInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic) double value;
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end

@class MFRouteStep;

SWIFT_CLASS_NAMED("Leg")
@interface MFRouteLeg : NSObject
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic, copy) NSString * _Nonnull startAddress;
@property (nonatomic, copy) NSString * _Nonnull endAddress;
@property (nonatomic) CLLocationCoordinate2D startCoordinate;
@property (nonatomic) CLLocationCoordinate2D endCoordinate;
@property (nonatomic, copy) NSArray<MFRouteStep *> * _Nonnull steps;
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end


SWIFT_CLASS_NAMED("Step")
@interface MFRouteStep : NSObject
@property (nonatomic, copy) NSString * _Nonnull instruction;
@property (nonatomic) enum MFManeuver maneuver;
@property (nonatomic, strong) MFRouteInfo * _Nonnull distance;
@property (nonatomic, strong) MFRouteInfo * _Nonnull duration;
@property (nonatomic) CLLocationCoordinate2D startCoordinate;
@property (nonatomic) CLLocationCoordinate2D endCoordinate;
@property (nonatomic, copy) NSArray<NSValue *> * _Nonnull coordinates;
@property (nonatomic, copy) NSString * _Nonnull streetName;
@property (nonatomic) enum MFTravelMode mode;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface MFRoute (SWIFT_EXTENSION(Map4dServices))
@end

typedef SWIFT_ENUM_NAMED(NSInteger, MFRouteWeighting, "Weighting", open) {
  MFRouteWeightingShortest = 0,
  MFRouteWeightingFastest = 1,
  MFRouteWeightingBalance = 2,
};


SWIFT_PROTOCOL("_TtP13Map4dServices14MFServiceError_")
@protocol MFServiceError
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


SWIFT_PROTOCOL("_TtP13Map4dServices13MFServiceTask_")
@protocol MFServiceTask
- (void)abort;
@end


SWIFT_CLASS("_TtC13Map4dServices19MFTextSearchOptions")
@interface MFTextSearchOptions : NSObject
@property (nonatomic, copy) NSString * _Nonnull text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic, strong) CLLocation * _Nullable location;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithText:(NSString * _Nonnull)text OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, MFTravelMode, open) {
  MFTravelModeCar = 0,
  MFTravelModeBike = 1,
  MFTravelModeFoot = 2,
};


SWIFT_CLASS("_TtC13Map4dServices22MFViewboxSearchOptions")
@interface MFViewboxSearchOptions : NSObject
@property (nonatomic) CLLocationCoordinate2D southWest;
@property (nonatomic) CLLocationCoordinate2D northEast;
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable types;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable tags;
@property (nonatomic, copy) NSDate * _Nullable datetime;
@property (nonatomic) NSInteger accuracy;
- (nonnull instancetype)initWithSouthWest:(CLLocationCoordinate2D)southWest northEast:(CLLocationCoordinate2D)northEast OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC13Map4dServices10MFWaypoint")
@interface MFWaypoint : NSObject
@property (nonatomic) CLLocationCoordinate2D coordinate;
@property (nonatomic, copy) NSString * _Nullable name;
- (nonnull instancetype)initWithCoordinate:(CLLocationCoordinate2D)coordinate name:(NSString * _Nullable)name OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (MFWaypoint * _Nonnull)clone SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface NSError (SWIFT_EXTENSION(Map4dServices)) <MFServiceError>
@property (nonatomic, readonly, copy) NSString * _Nonnull errorCode;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


@interface NSURLSessionTask (SWIFT_EXTENSION(Map4dServices)) <MFServiceTask>
- (void)abort;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
#endif
